---
- name: Network Backup
  connection: network_cli
  gather_facts: false
  hosts: network
  tasks:
    - name: Backup configs
      nxos_config:
        backup: yes
        backup_options:
          dir_path: configs/
          filename: "{{ inventory_hostname }}.conf"
