---
- name: Deploying Infrastructure
  connection: network_cli
  gather_facts: false
  hosts: leaf4,spine2
  roles:
    - base
    - features
    - interfaces
    - ospf
    - pim
    - bgp
    # - enhancements
    - vlan_vxlan