---
- name: Deploying Infrastructure 
  connection: network_cli
  gather_facts: false
  hosts: leafs
  roles:
    # - base
    # - features
    # - interfaces
    # - ospf
    # - pim
    # - bgp
    # - enhancements
    - vlan_vxlan