- name: Configure base level interface settings
  nxos_interfaces:
    config:
      - name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        enabled: "{{ item.value.enabled }}"
        mtu: "{{ item.value.mtu }}"
        mode: "{{ item.value.mode }}"
  with_dict: "{{ interfaces }}"
  when: interfaces is defined

- name: Configure loopback interface settings
  nxos_l3_interfaces:
    config:
      - name: "{{ item.value.name }}"
        ipv4:
          - address: "{{ item.value.ip_address }}"
  with_dict: "{{ loopbacks }}"
  when: loopbacks is defined

- name: Configure nve interfaces
  nxos_vxlan_vtep:
    interface: nve1
    host_reachability: yes
    source_interface: Loopback0
    shutdown: no
  when: "'leafs' in group_names"