- name: Enable features for fabric
  nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: "{{ features }}"
  when: features is defined

- name: enable fabric forwarding feature
  nxos_config:
    lines: feature fabric forwarding