hostname: leaf2

interfaces:

  Ethernet1/1:
    name: Ethernet1/1
    enabled: True
    mode: layer3
    mtu: 9216
    description: connection to spine1
    ospf_enabled: True
    pim: True

  Ethernet1/2:
    name: Ethernet1/2
    enabled: True
    mode: layer3
    mtu: 9216
    description: connection to spine2
    ospf_enabled: True
    pim: True

  Ethernet1/3:
    name: Ethernet1/3
    enabled: True
    mode: layer2
    vlan: 20
    mtu: 9216
    description: connection to server2
    ospf_enabled: False
    pim: False

loopbacks:

  loopback0:
    name: loopback0
    ip_address: 192.168.0.4/32
    description: loopback 0
    ospf_enabled: True
    pim: True

vlans:
  - id: 20
    description: Data_VLAN
    enabled: True
    vn_segment: 100020
    l3_vni: False
    l3_enabled: True
    ip_address: 10.20.1.254/24
    fabric_forwarding: True
    suppress_arp: True
    mcast_group: 224.1.1.192
    vrf_member: TENANT1
    assoc_vrf: False
    ip_forward:
    
  - id: 999
    description: VLAN_for_L3VNI
    enabled: True
    vn_segment: 100999
    l3_vni: True
    l3_enabled: True
    ip_address:
    fabric_forwarding: False
    suppress_arp: False
    mcast_group:
    vrf_member: TENANT1
    assoc_vrf: True
    ip_forward: True

vrfs:

  - name: TENANT1
    vn_segment: 100999
    enabled: True
    rd: auto
    address_family: address-family ipv4 unicast
    networks:
      - id: 1
        network: 10.20.1.0/24
        advertise: advertise l2vpn evpn