- name: configure hostname
  nxos_config:
    lines: 
      - hostname {{ hostname }}
      - cli alias name wr copy run start
    save_when: modified
  when: hostname is defined

- name: configure motd banner
  nxos_banner:
    banner: motd
    text: |
      BGP EVPN VXLAN LAB
      Thank you Packetflow.co.uk

- name: configure exec banner
  nxos_banner:
    banner: exec
    text: |
      If you are not authorized to enter....
      please log out :)